### ISSUE TITLE
Touch IRQ Test example

### ISSUE THREAD

**Issue by Donziboy2** [PaulStoffregen/XPT2046_Touchscreen#11]
Still new to github and have not been able to wrap my head around it yet.  Here is a .txt of an example code that uses the new tirqTouched function.  Use it how you see fit ;)

[TouchIRQTest.txt](https://github.com/PaulStoffregen/XPT2046_Touchscreen/files/1533456/TouchIRQTest.txt)

**Comment by PaulStoffregen** [comment]
Added.  https://github.com/PaulStoffregen/XPT2046_Touchscreen/commit/f359f123fbc95370f4fe580817771e0267251c79  Thanks!

**Comment by Donziboy2** [comment]
Happy to help :)
