### ISSUE TITLE
Bump Version

### ISSUE THREAD

**Issue by Professor-plum** [PaulStoffregen/XPT2046_Touchscreen#15]
I see you added the setRotation function since version 1.2
Can you please bump the version number so user libraries update automatically?

Thanks

**Comment by ristohelkio** [comment]
One more vote for bumping version number. The library now claims to be version 1.2 but is something different.

**Comment by PaulStoffregen** [comment]
Done https://github.com/PaulStoffregen/XPT2046_Touchscreen/commit/5ccb951d346017005b1fff7289bf19a1904e2de3

https://github.com/PaulStoffregen/XPT2046_Touchscreen/releases/tag/v1.3
