### ISSUE TITLE
Issue with April 2018 release of ESP32 support

### ISSUE THREAD

**Issue by hsgentry** [PaulStoffregen/XPT2046_Touchscreen#16]
I have used Mini Grafx and XPT2046_Touchscreen and Arduino IDE 1.8.2 with ESP32 for many projects with excellent results.  With the April 2018 release of the ESP support there is a problem.  The display with Mini Grafx goes completely white.  This happens very rarely, sometimes it will work OK for a day or two sometimes it will fail in an hour.  The processor is still running and the touch still works, the display is just all white. Only a reboot will start make the display work again.

I have traced this to some issue with the touch screen.  If the touch screen is enabled, but the code never checks for a touch it will run OK.  If the code periodically checks for a touch it will eventually fail.

**Comment by PaulStoffregen** [comment]
Can this old issue be closed?

**Comment by hsgentry** [comment]
Yes
