### ISSUE TITLE
Compile ERROR  with ESP8266(NodeMCU-1.0(ESP-12E Module)

### ISSUE THREAD

**Issue by 2969773606** [PaulStoffregen/XPT2046_Touchscreen#30]
Compile ERROR:

D:\Documents\Arduino\libraries\ILI9341_t3-master/ILI9341_t3.h: In member function 'void ILI9341_t3::waitFifoNotFull()':

D:\Documents\Arduino\libraries\ILI9341_t3-master/ILI9341_t3.h:445:9: error: 'KINETISK_SPI0' was not declared in this scope

    sr = KINETISK_SPI0.SR;

         ^

D:\Documents\Arduino\libraries\ILI9341_t3-master/ILI9341_t3.h: In member function 'void ILI9341_t3::waitFifoEmpty()':

D:\Documents\Arduino\libraries\ILI9341_t3-master/ILI9341_t3.h:453:9: error: 'KINETISK_SPI0' was not declared in this scope

    sr = KINETISK_SPI0.SR;

**Comment by 2969773606** [comment]
Thank you very much for any advice.

**Comment by FrankBoesing** [comment]
Ili9341_t3 is for Teensy 3, only. No Chance to use it with ESP.

**Comment by PaulStoffregen** [comment]
Of course ILI9341_t3 doesn't compile for ESP.  It's a library for Teensy.

Why you're reporting ILI9341_t3 on this library's repository makes no sense.

**Comment by 2969773606** [comment]
Thank you very much, it make sense.

**Comment by 2969773606** [comment]
> Ili9341_t3 is for Teensy 3, only. No Chance to use it with ESP.

Thank you very much, it make sense.

**Comment by 2969773606** [comment]
> Of course ILI9341_t3 doesn't compile for ESP. It's a library for Teensy.
Thank you very much, it makes sense.
