### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by ilka-schulz** [PaulStoffregen/XPT2046_Touchscreen#51]
This project currently has no license file which causes legal uncertainty when using this library for non-private projects. Maybe add MIT or Apache license?

**Comment by PaulStoffregen** [comment]
https://github.com/PaulStoffregen/XPT2046_Touchscreen/blob/5d5120e93ab5d28b3f1db6d754819c354c2da019/XPT2046_Touchscreen.cpp#L4
