### ISSUE TITLE
Please release new version which includes the IRQ constructor

### ISSUE THREAD

**Issue by squix78** [PaulStoffregen/XPT2046_Touchscreen#6]
Hi Paul

Thank you so much for this driver. I first tried this one here https://github.com/spapadim/XPT2046 but it caused some issues on a shared SPI bus. I plan to use the touch screen driver on my plane spotter color project (https://blog.squix.org/2017/01/esp8266-planespotter-color.html) but the currently released version does not contain the constructor with the second parameter for the interrupt. Can you please release version 1.2 so it will be available through the platformio and Arduino IDE library manager? This would be a lot easier for my users which sometimes are on beginner level. That would be awesome!

Regards,
Daniel

**Comment by PaulStoffregen** [comment]
https://github.com/PaulStoffregen/XPT2046_Touchscreen/releases/tag/1.2
