### ISSUE TITLE
attachInterrupt() in begin() method. 

### ISSUE THREAD

**Issue by prenticedavid** [PaulStoffregen/XPT2046_Touchscreen#7]
If you specify an IRQ pin,   on a Uno the ISR() only gets attached if you use digitalPinToInterrupt(tirqPin)

        attachInterrupt( digitalPinToInterrupt(tirqPin), isrPin, FALLING );  //.kbv

David.

**Comment by SuitableOrNot** [comment]
Same Thing on an Mega2560, I modified the library to work with my LCD-Shield by modifying the "attachInterrupt"-Line within begin() in `XPT2046_Touchscreen.cpp` to:
```
bool XPT2046_Touchscreen::begin()
{
	SPI.begin();
	pinMode(csPin, OUTPUT);
	digitalWrite(csPin, HIGH);
	if (255 != tirqPin) {
		pinMode( tirqPin, INPUT );
		attachInterrupt( digitalPinToInterrupt(tirqPin), isrPin, FALLING );
		isrPinptr = this;
	}
	return true;
}
```

And now it works like a charm :)
Thank you for this library 👍
